### ISSUE TITLE
skip KV if there are no secrets for the 'vkv snapshot'

### ISSUE THREAD

**Issue by patrickdung2022** [FalcoSuessgott/vkv#201]
```
$ vkv snapshot save -d backup1
created backup1
created backup1/kv-project1.yaml
[ERROR] could not read secrets from kv-project2/: no secrets in kv-project2 found.
```

In vkv 0.6.0, if there are no secrets in the KV, the program quit and stop going through other kv.

**Comment by FalcoSuessgott** [comment]
Thanks for reporting! #204 should fix it, you might want to try it. I decided to add the `--skip-errors` flag, which is also available in the `vkv export` command. So the user is aware that some exported snapshot files might a not be complete, rather than just silently continuing on errors. I hope that does work for you.
